---
  # - name: Install python
  #   hosts: ubuntu
  #   tasks:
  #     - name: apt update and install
  #       apt:
  #         name: python3
  #         update_cache: yes
  - name: Print os facts
    hosts: all
    tasks: 
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"