apiVersion: v1
kind: Namespace
metadata:
  name: python-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      namespace: default
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: cr.yandex/crpa6oiaqi6o9ri05k8u/python-api:__VERSION__
          imagePullPolicy: Always
